config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root "pages#show", page: "home"
  get '/about',     to: 'pages#about' # do I want this page?
  get '/features',  to: 'pages#features' # do I want this page?
  get '/home',      to: 'pages#home'
  #get '/register', to: 'users#new' # manually mapping user registration to /register instead of /users/new -> therefore not listed under resources
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new' # links to log in; page for a new session (login)
  post '/login',    to: 'sessions#create' # create a new session (login) ; arranges to route POST request to the Sessions#create action.
  get '/logout',    to: 'sessions#destroy' # deletes a session (log out)
  resources :users  #using all the actions
  resources :projects, except: [:destroy]
  resources :tasks do
      resources :task_entries
  end
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #   resources :account_activations, only: [:edit] #add a route for the account activations 'edit' action
  # lines 18 brings the index
 resources :customers, except: [:destroy]
  # start nesting from line 18 - using relationships to creates paths
  resources :customers do # 'resouce' refers to the controller; all the RESTful routes map to companies
    resources :projects do
      resources :tasks do
        resources :task_entries
      end
    end
  end
end

#   resources :task_entries do
#         get :start_time
#       end
#   resources :task_entries do
#         post :stop_time
#       end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user #taks belong_to (a) user- singular
  belongs_to :project #tasks belong_to (a) project
  has_many :task_entries

  def has_running_task_entries?
     task_entries.any? { |task_entry| task_entry.duration.nil? } #implies task
  end

  def total_duration #calucate duration
    task_entries.sum(&:duration)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # url task/1
  def show
    puts "***** #{params}"
    @task = Task.find params[:id] # @task is available for the view
  end

  def index #calls index method, so we're defining it here
    @tasks = Task.all # Task is the class
  end

  def new
    @task = Task.new
  end

  def edit #enables 'edit' for tasks
     @task = Task.find params[:id]
  end

  def update # should enable 'edit' to be saved; in edit.html.erb
    @task = Task.find(params[:id])
      if @task.update(task_params)
        flash[:success] = "Task updated!"
        redirect_to @task
      else
        render 'edit'
      end
    end

  def create #this could also be 'def new'?
      # getting parameters the user is entering, this info gets
      # passed to the Task controller; takes attrbutes and makes new customer
      @task = Task.new(task_params) #using strong params in the 'create' action
      #@task.user = current_user
    if @task.save
      flash[:notice] = "Task created!"
      redirect_to @task #or root_path # the user 'create' action with a save and a redirect
    else
      render :new #if there's a problem creating the new customer
    end
  end

  private # no public access to parameters

  def task_params
    params.require(:task).permit(:project_id, :user_id, :task_name)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>
<h1>Edit Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @task, local: true) do |f| %> <!-- follow pattern for sessions_controller -->

      <%= f.label :project_name%> <!-- drop down menu -->
      <%= f.collection_select(:project_id, Project.all, :id, :name_with_company, :prompt => 'Select') %>

      <%= f.label :task_name %>
      <%= f.text_field :task_name, class: 'form-control' %>
      <div>

      <%= f.submit "Save Task", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<!-- in the taks model - project_id, user_id, task_name -->
<!-- we just need to "edit" the task; however we do want the information for project + company -->

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tasks</h1>


<%= link_to 'New Task', new_task_path %>
<table>
    <thead>
        <tr>
          <th>Task Name</th>
          <th>Project Name</th>
          <th>Company Name</th>
          <th>Duration</th>
          <th colspan="3"></th>
        </tr>
    </thead>

    <tbody> <!-- need to have header to tell what data displaying; which company is't for? -->
      <% @tasks.each do |task| %> <!--|task| gives access to each one of the task table -->
        <tr>
          <td><%= task.task_name%></td>
          <td><%= task.project.project_name%></td>
          <td><%= task.project.customer.company%></td>
          <td><%= "#{task.total_duration} minutes" %></td>
          <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%#= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
       <% end %>
    </tbody>
  </table>

  <br>


<!-- <div>
  <#% (1..50).each do |i| %>
  <div>
    <%#= i %>
  </div>
<%# end %>
</div> -->

app/views/tasks/new.html.erb
<% provide(:title, 'New task') %>
<h1>New Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @task, local: true) do |f| %> <!-- follow pattern for sessions_controller -->

      <%= f.label :project_id, "Project | Company" %> <!-- 'company' can be any attribute on Customer;-->
      <%= f.collection_select(:project_id, Project.all, :id, :name_with_company, :prompt => 'Select') %>

      <%= f.label :task_name, "Task Name" %>
      <%= f.text_field :task_name, class: 'form-control' %>

      <div>

      <%= f.submit "Create New Task", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, "Tasks") %> <!-- describe data lin 5 -11 ; in table form -->
<div>
  <strong>Project Id:</strong>
  <%= @task.project_id %>
</div>
<br>
<div>
  <strong>Username:</strong>
<!-- tasks belongs_to :user -->
  <%= @task.user.name%> <!--name according to data model -->
</div>
<br>
<div>
  <strong>Project Name:</strong>
<!-- tasks belongs_to :project -->
  <%= @task.project.project_name %>
  </div>
  <br>
  <div>
    <strong>Task Entry:</strong>
  </div>
<!-- tasks has_many :task_entry -->
  <% @task.task_entries.each do |task_entry| %> <!-- "entries" -->
    <br>
    <div>
      &ensp;<strong>Time Entry ID:</strong>
      <%= task_entry.id %> &ensp;
      <br>
      <strong>Note:</strong>
      <%= task_entry.note %>
      <br>
      <strong>Start Time:</strong> &ensp;
      <%= task_entry.start_time %>
      <strong>End Time:</strong> &ensp;
      <%= task_entry.stop_time %>
      <strong>Duration:</strong> &ensp;
      <%= task_entry.duration %>
      <br>
      <% if task_entry.duration.nil? %> <!-- start is a 'create' -->
        <%= button_to 'Stop Time Entry', task_task_entry_path(@task, task_entry), method: :put %>
      <% end %>
    <% end %>
  </div>

  <div>
    <% unless @task.has_running_task_entries? %> <!-- start is a 'create' -->
      <%= button_to 'Start Time Entry', task_task_entries_path(@task), method: :post %>
    <% end %>
  </div>