config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root "pages#show", page: "home"
  get '/about',     to: 'pages#about' # do I want this page?
  get '/features',  to: 'pages#features' # do I want this page?
  get '/home',      to: 'pages#home'
  #get '/register', to: 'users#new' # manually mapping user registration to /register instead of /users/new -> therefore not listed under resources
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new' # links to log in; page for a new session (login)
  post '/login',    to: 'sessions#create' # create a new session (login) ; arranges to route POST request to the Sessions#create action.
  get '/logout',    to: 'sessions#destroy' # deletes a session (log out)
  resources :users  #using all the actions
  resources :projects, except: [:destroy]
  resources :tasks do
      resources :task_entries
  end
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #   resources :account_activations, only: [:edit] #add a route for the account activations 'edit' action
  # lines 18 brings the index
 resources :customers, except: [:destroy]
  # start nesting from line 18 - using relationships to creates paths
  resources :customers do # 'resouce' refers to the controller; all the RESTful routes map to companies
    resources :projects do
      resources :tasks do
        resources :task_entries
      end
    end
  end
end

#   resources :task_entries do
#         get :start_time
#       end
#   resources :task_entries do
#         post :stop_time
#       end

app/models/user.rb
class User < ApplicationRecord #validation

  has_many :tasks

  has_secure_password #validations: false
      #validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  #validates :password, presence: true, on: :create, length: {minimum: 5} # on: :create means that a password has to be present when creating a new user, but not when updating user details
end

#when we create user, needs a pw
#when updating user email, pw doesn't need to change

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before the action runs, set user
  # for the above actions, we have to have a user to work with

  def show # /users/3
    @user = User.find(params[:id])
  end

  def index # user's index can be navigaged from the nav bar
    @users = User.all
  end

  def new #adding @user variable to the 'new' action
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def update #enable 'edit'be saved; in edit.html.erb
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create #this could also be 'def new'
    #@user = User.new(user_params) #will find users based on paras
      @user = User.new(user_params) #using strong params in the 'create' action
    if @user.save
      session[:user_id] = @user.id # to automatically login a user that signed up
      flash[:notice] = "You are registered!"
      redirect_to @user #or root_path # the user 'create' action with a save and a redirect
    else
      render :new
    end
  end

  private # no public access to parameters

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def set_user # set_user method
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="well">
    <%= form_for @user do |f| %>
      <div class="control-group">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="control-group">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <%= f.submit "Register", class: "btn btn-success" %>
    <% end %>
</div>

app/views/users/_navigation.html.erb
<!-- _navigation.html.erb -->
<!--to show register link, when logged out -->

<% if logged_in? %>
  <div class='nav_item'>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
    <div class='nav_item'>
    <%= link_to 'Log out', logout_path, class: 'btn btn-small' %>
  </div>
<% else # logged out %>
  <div class='nav_item'>
    <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
  </div>

  <div class="nav_item">
    <%= link_to "Register", register_path, class: "btn btn-success btn-small" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %> <!-- form = partial -->

<%= link_to 'Show', @user %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %> <!-- follow pattern for sessions_controller -->
      <%= render 'shared/error_messages' %> <!-- displays error messages on the signup form -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |