config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root "pages#show", page: "home"
  get '/about',     to: 'pages#about' # do I want this page?
  get '/features',  to: 'pages#features' # do I want this page?
  get '/home',      to: 'pages#home'
  #get '/register', to: 'users#new' # manually mapping user registration to /register instead of /users/new -> therefore not listed under resources
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new' # links to log in; page for a new session (login)
  post '/login',    to: 'sessions#create' # create a new session (login) ; arranges to route POST request to the Sessions#create action.
  get '/logout',    to: 'sessions#destroy' # deletes a session (log out)
  resources :users  #using all the actions
  resources :projects, except: [:destroy]
  resources :tasks do
      resources :task_entries
  end
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #   resources :account_activations, only: [:edit] #add a route for the account activations 'edit' action
  # lines 18 brings the index
 resources :customers, except: [:destroy]
  # start nesting from line 18 - using relationships to creates paths
  resources :customers do # 'resouce' refers to the controller; all the RESTful routes map to companies
    resources :projects do
      resources :tasks do
        resources :task_entries
      end
    end
  end
end

#   resources :task_entries do
#         get :start_time
#       end
#   resources :task_entries do
#         post :stop_time
#       end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%#= link_to "#", root_path %>
    <nav>
      <div class="navbar-header" style="text-align: right;">
             <!-- "==" booleans -->
         <% unless controller_name == "customers" %>
          <%= link_to "customers", customers_path %> |
         <% end %>

         <% unless controller_name == "projects" %>
          <%= link_to "projects", projects_path %> |
        <% end %>

        <% unless controller_name == "tasks" %>
          <%= link_to "tasks", tasks_path %> |
        <% end %>

        <% unless controller_name == "task_entries" %>
         <%#= link_to "task_entries", task_entries_path %> |
        <% end %>

         <%= link_to "Log in", login_path %> |
         <%= link_to "users", users_path %> |
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>